# Generated by Django 4.2.2 on 2023-07-08 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdataApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
    ]
