# Generated by Django 4.2.2 on 2023-07-08 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdataApi', '0002_profile_dark_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dark_mode',
        ),
    ]
