# Generated by Django 4.2.2 on 2023-07-11 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApi', '0002_remove_producto_id_producto_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
