# Generated by Django 4.2.2 on 2023-07-12 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tiendaApi', '0004_alter_producto_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='propietario',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
