# Generated by Django 4.2.2 on 2023-07-12 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApi', '0007_carrito_elementocarrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='propietario',
        ),
    ]
