# Generated by Django 4.2.2 on 2023-07-12 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApi', '0009_boleta_detalle_boleta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_boleta',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendaApi.producto'),
        ),
    ]
