# Generated by Django 4.2.2 on 2023-07-12 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApi', '0010_alter_detalle_boleta_id_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='carrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tiendaApi.carrito'),
        ),
    ]
